### PR TITLE
Add telegram alert functionality

### PR DESCRIPTION
**Pull request by mariusoei**
Hi,

thank you for the great work on this bot.
The telegram bot API is very simple, so I added a telegram notification functionality (can't read back codes, only sends alerts).
I tested it using the "--alert" flag and it seems to work.

I also added the settings entries. The bot must first be created in the Telegram app using the BotFather. An explanation of the process is given e.g. here: https://www.techthoughts.info/how-to-create-a-telegram-bot-and-send-messages-via-api/

Marius

### CODE REVIEW

**Comment by alfonsrv** [comment]
Pull request looks solid – Merging.  
Thanks for contributing @mariusoei!

**Comment by alfonsrv** [comment]
@mariusoei I added a setup guide for Telegram at [ALERTS.md](https://github.com/alfonsrv/impf-botpy/blob/main/docs/ALERTS.md) – mind reviewing?

**Comment by mariusoei** [comment]
It looks good, but I believe one step is missing. Afaik, in order for the bot to be able to message you, you first need to send /start to your newly created bot.

**Review by alfonsrv — COMMENTED** [review]
Changed the `telegram_send` to be more *pythonic*

```python
def telegram_send(message: str) -> None:
    api_token = settings.TELEGRAM_BOT_TOKEN
    chat_id = settings.TELEGRAM_BOT_CHATID

    url = f'https://api.telegram.org/bot{api_token}/sendMessage'
    params = {
        'chat_id': chat_id,
        'parse_mode': 'Markdown',
        'text': message
    }

    response = requests.get(url, params=params, headers=HEADERS)
    logger.debug(response)
```

**Pull request merged**
