### PR TITLE
Add headless browser mode

### PR DESCRIPTION
**Pull request by Papierkorb**
Hello,

I wasn't able to run this tool on my little home server (Which doesn't have a running X11 or anything).
So I added a setting to make it run headless (And defaulted it to true).

Cheers!

### CODE REVIEW

**Comment by alfonsrv** [comment]
The issue about running it headless is, that right now you cannot actually book an appointment automatically yet (as described in [README.md - Workflow](https://github.com/alfonsrv/impf-botpy#workflow)), but need to choose your appointment manually. This is not only to prevent abusing, but also because I didn't want to put people's opportunity in jeopardy when they have a chance to book appointments - e.g. if the HTML form changes. Headless might also be intuitive for the user.  

I thought about adding Docker support, to support it running it on a server. What do you think?

**Comment by Papierkorb** [comment]
Oh yeah, Docker would be great.  I've been using Puppeteer in a NodeJS-based app with great success recently.

Mh, would it be possible to have it either use the Notification service to let the user choose one?  At least Telegram could do it.  Otherwise, maybe an automatic booking feature where you can give the time range, or allow a "Give me anything" type of setting.

**Comment by alfonsrv** [comment]
Yeah, I'm considering adding an option to fully streamline the process of booking appointments remotely. Was hesitant previously regarding people possibly abusing the bot or it breaking when the HTML form changes. The main issue so far though is getting to the booking-step in the process and having sufficient test coverage.  

Don't really want to choose a `random` or `closest` appointment, as it seems to be counterproductive to cause such an uncoordinated appointment bombardement when people are likely to not actually use them.

edit: Docker support is already done. Just have to push it to what is now called `main`

**Comment by alfonsrv** [comment]
Just added Docker support. Can you check if that's sufficient for your requirements?

**Pull request closed without merging**
