### PR TITLE
Requirements: Pin urllib3 version to 1.26.4

### LINKED ISSUE #14: Instant code Generation No Response
For some reasons, Im unable to generate a Code using the --code method. I guess the error is some kind of rate limiting.

I get two kinds of errors:
Either I get ratelimited, have to wait some time and then get this response:

`An error occurred requesting code from server; response [200]`

Or I am not forced to wait some time, but then I instantly get 

`An error occurred requesting code from server; response [429]`

No matter, which error occurs, this is always the last line in the log:

`[INFO] <impf.api.api.py:43>  {}`

So I dont seem to get any response at all.

As a User-Agent, I used the default one and `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36`

I tried it with 2 different Phonenumbers and 3 different Emails, so I dont think its because of that.
The locations I tried are 88444 Ummendorf, 88212 Ravensburg and 89073 Ulm

I also tried to wait 30 Minutes after some tries and 3 different IPs, and also from my server, nothing worked.

Also I tried it in Docker and natively on Windows, both time the same error

```
2021-05-20 18:57:06,128 - [INFO] <impf.browser.browser.py:140>  89073: Navigating to ImpfterminService
2021-05-20 18:57:08,545 - [INFO] <impf.browser.browser.py:153>  89073: Selected Bundesland: Baden-Württemberg           
2021-05-20 18:57:08,760 - [INFO] <impf.browser.browser.py:161>  89073: Selected Impfzentrum: 89073 Ulm, Zentrales Impfzentrum Ulm
2021-05-20 18:57:27,263 - [INFO] <impf.api.api.py:33>  API: Attempting to get Vermittlungscode from server              
2021-05-20 18:57:30,719 - [ERROR] <impf.api.api.py:44>  API: An error occurred requesting code from server; status code [429]                                                                                                                   
2021-05-20 18:57:30,720 - [INFO] <impf.api.api.py:45>  API: Response: {}
```

Edit: 
I tried to put the steps done in the API.py into a standalone script, and here I constistently get Statuscode 200, but no returned data

### PR DESCRIPTION
**Pull request by MarcelBochtler**
Resolves #14.

### CODE REVIEW

**Comment by alfonsrv** [comment]
Unfortunately urllib3 is switching their SSL verification method, leading to the first major bug in their library in what's probably a decade. Even `pip` is affected – deliberately downgraded due to https://github.com/alfonsrv/impf-botpy/issues/4  

It's interesting this is fixing #14 

edit: Seems like the downgrade got lost in f9ba21bd45f0e32d045754515a0b10012b8dcce4

**Comment by alfonsrv** [comment]
Obligatory: *What do you think we should do*

**Comment by MarcelBochtler** [comment]
I'm not sure as I don't have a lot experience with python's dependency system.
I tried to use `urllib3`'s latest master by adding `git+git://github.com/urllib3/urllib3@c55e0840b1e9596941b4279a633264aae976b3e4#egg=urllib3` to `requirements.txt`.
But this fails because `requests` requires a lower version:
```
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
requests 2.25.1 requires urllib3<1.27,>=1.21.1, but you'll have urllib3 2.0.0.dev0 which is incompatible.
```

Edit: I guess we should investigate why the instant code generation fails with `1.25.11` but succeeds with `1.26.4`.
I found our just by trial and error.

**Comment by alfonsrv** [comment]
Just tried debugging this a bit and not sure whether or not the two libraries actually make the main difference. 

I set up two `virtualenv`s, one with `urllib3==1.25.11` and one with `urllib3==1.26.4`. In order to see what might be wrong and if/how the requests differ I started BurpSuite and configured an Intercept Proxy – it's important to also check `Intercept responses`. Requests can be sent through the proxy by setting `..., proxies={'https': 'http://127.0.0.1:13370'}, verify=False`.  

I initially had issues requesting with `1.25` in this setup without the proxy, and `1.26` worked well. As soon as I sent the requests through the proxy, requests with `1.25` worked just as well. I tried setting just `verify=False` thinking it might have something to do with a possible incompatibility of `requests==2.25.1` and `urllib3==1.25.11` or the SSL change made in `1.26`, but got spotty results.  

So far I have thought of the servers as independent instances, where shadow banning users is not synchronized and code creation isn't either. I'm mentioning this, because there is a slight possibility that the server also authenticates requests made through `1.25` throughout all servers for a certain time period as soon as one successful setup has been made with one through `1.26`. Just a thought though.  

Can you confirm whether or not you can replicate a similar behavior?

edit: Just started thinking – it might have something to do with the SSL handshake negotiated with the server. As I'm getting no good results when using `verify=False`, but only after adding the proxy. When using BurpSuite as a proxy it is effectively making the handshake, probably using a stronger cipher suite. It might be a way of them to detect bots by offering deprecated crypto algorithms that are not supported by common Browsers anymore. Or something along those lines..

**Comment by alfonsrv** [comment]
Digging into it with Wireshark it becomes clear Chrome is negotiating a TLS 1.3 connection with `TLS_AES_256_GCM_SHA384`. `urllib 1.26` is communicating with the REST API with TLS 1.3 and `urllib 1.25` is stuck on TLS 1.2. – Quite impressive they went to such lengths to detect subtleties like this.  

There is no viable way (I know of) to force `requests` to use TLS 1.3 or said Cipher Suite, especially as there seem to be a lot of pit falls regarding OS dependencies. Merging Pull Request to main.  

Thanks for contributing.

**Pull request merged**
