### PR TITLE
Added feature RESCAN_VERMITTLUNGSCODE to retry getting a Vermittlungs…

### PR DESCRIPTION
**Pull request by lusor**
…code without while staying on the page

### CODE REVIEW

**Comment by lusor** [comment]
Looks like there is no issue with shadow bans here as in #19. WAIT_RESCAN_VERMITTLUNGSCODE could be hardcoded, as well

**Comment by alfonsrv** [comment]
Hey Volker,

the landing page is the only page where the `429` is actively used – so it applies here. Didn't add this setting yet, as it adds very little benefit to the over all workflow imo and therefore unnecessary complexity for first-time users. What do you think?

Alfons

**Comment by lusor** [comment]
Hi Alfons,

if you're referring to WAIT_RESCAN_VERMITTLUNGSCODE, I guess, after you merged #19, this also should be configurable.

If you're referring to the retry feature RESCAN_VERMITTLUNGSCODE itself, I am trying to get a Vermittlungscode in one location for some days now. I have no idea, under which circumstances this will be successful, but the option to check more often without getting stuck in the waiting room is appealing.

Cheers,
Volker

**Comment by alfonsrv** [comment]
The reason I added the behavior as is, is because the website sometimes behaves differently when you reload it from scratch.

**Comment by lusor** [comment]
> The reason I added the behavior as is, is because the website sometimes behaves differently when you reload it from scratch.

Well, that's an argument not to merge this. Luckily, I now have my last Vermittlungscode, so I won't be too unhappy ;)

Alas, I have not much experience with the behavior of the website.

**Comment by alfonsrv** [comment]
Today I realized there's multiple cookies in play, some of which are only set *some time* during the process.

Closing this due to the reasons mentioned.

BR, Alfons

**Pull request closed without merging**
