### PR TITLE
Update Step 7 of selenium-install-instruction [Windows]

### PR DESCRIPTION
**Pull request by Shirkanesi**
Chromedriver can be placed in the same directory as the main.py
Unexperienced users will be more comfortable putting an unknow file somwhere in their downloads-folder instead of System32 or messing with %PATH%

### CODE REVIEW

**Comment by alfonsrv** [comment]
Hey, thanks for your PR. 

Are you sure that's true? – E.g. if you execute the script while in `%USERPROFILE%` directory as such: `python .\Downloads\impf-botpy\main.py`

**Comment by Shirkanesi** [comment]
Yes. I've just tested it realy quickly by putting the bot-directory into %temp%. When chromedriver.exe is located in the same directory, everything works. Renaming it to xchromedriver.exe lead to 
_"selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home"_

So i'm pretty sure this works.

**Comment by alfonsrv** [comment]
Indeed does – I'm surprised. Seems like the `os.chdir` in `settings.py` is doing the trick.

Thanks for the pointer. We'll have to see on how to formulate it; I'm not happy with the way it is right now. As it's geared towards dummies it's best to have a concise Step-by-Step guide. 

In the suggested change users are required to leave `Selenium Installation` unfinished, go over `Python Installation` and `Download Project` and to then jump back to the last step of `Selenium Installation` to move the `chromedriver.exe` in the desired directory. This is usually not ideal as less tech-savvy users need clear instructions and goals.

Even if we moved `Selenium Installation` somewhere else in the process, the same issue arises. As people would have to `Download Project` first, then put the `chromedriver.exe` in the bot's folder and finally go back to the last steps of `Download Project` to execute the bot.

**Comment by alfonsrv** [comment]
Maybe like this?

7. Put the `chromedriver.exe` from the zip-Archive in the `impf-botpy` folder after downloading the project (further down) – alternatively you can:
  * put it into `C:\Windows` straight away or if you're experiencing issues
  * put it somewhere else, but you should make sure the folder is in your %PATH%-variable
  * point the `SELENIUM_PATH` in `settings.py` to the path of the `chromedriver.exe` explicitly

**Comment by Shirkanesi** [comment]
Sounds good to me.

**Comment by alfonsrv** [comment]
Added formatting – merging to `main`. 

Thank you for contributing. BR,
Alfons

**Pull request merged**
